### PR TITLE
use case range instead of cap [skip ci]

### PR DESCRIPTION
**Pull request by paulflang**

### CODE REVIEW

**Comment by anandijain** [comment]
unnecessary. if you really need this just have the change locally but it doesnt do anything

**Comment by paulflang** [comment]
I'd like to use this repo for debugging SBMLToolkit. It wastes hours running hundreds of cases just for checking if the bugfix for one case worked. What is your rational for having an upper but not lower boundary? In particular, what disadvantages come with a lower boundary?

**Comment by anandijain** [comment]
why aren't you just running on the file you're testing? it makes no sense to run all of them for a single test file

**Comment by paulflang** [comment]
Cumbersome API with lower_one requiring a dataframe as argument. Thanks for changing that, that helps already. Also a bit cumbersome to add that both, lower_one and verify_case both need the whole path as input. Could be solved by adding a utility function `get_case_dir("00001")` so you can `verify_case(get_case_dir("00001"))`. How does that sound? Defo the README also needs better instructions how to use this repo.

**Pull request closed without merging**
