### PR TITLE
correct number of steps for calculating ts

### PR DESCRIPTION
**Pull request by paulflang**

### CODE REVIEW

**Comment by anandijain** [comment]
im sure ur right that this is a fix, but this seems odd to me. how was it possible that any cases at all passed if the number of steps was wrong all along?

**Comment by paulflang** [comment]
very odd. we should have gotten a dimension mismatch when comparing ground truth and simulation, right?

**Comment by anandijain** [comment]
yeah thats what id expect

**Comment by anandijain** [comment]
like either this pr gives dimension errors for every test case or how it is now gives errors for every test case

**Comment by paulflang** [comment]
wait a sec for my commit

**Comment by anandijain** [comment]
doh. thanks for catching all my dumbass mistakes

**Comment by anandijain** [comment]
i could check this myself, but shouldn't `size(solm) == size(results)`? why do we do `results[1:end, 2:end]`?

**Comment by paulflang** [comment]
idk. you did `results[1:end-1, 2:end]`. i corrected to `results[1:end, 2:end]`. i think we skip the firs column as it might be the time column.

**Comment by anandijain** [comment]
yeah thats right, thats what it is. thakns

**Pull request merged**
